from pydantic import BaseModel, ConfigDict, EmailStr, Field
from typing import Optional
from datetime import datetime
import uuid

from app.domain.enums import UserRole

class UserBase(BaseModel):
    email: EmailStr
    full_name: str
    hostel: Optional[str] = None

class UserCreate(UserBase):
    """
    Schema used when creating a new user.
    Requires linking to a specific role ID.
    """
    role_id: uuid.UUID

class UserResponse(UserBase):
    """
    Schema used to return user data to the client.
    Includes the UUID and timestamps generated by the database.
    """
    id: uuid.UUID
    role_id: uuid.UUID
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)
