// Phase 2 — Core Primitives
export { Button } from '@/components/ui/Button'
export type { ButtonProps } from '@/components/ui/Button'
export { Input } from '@/components/ui/Input'
export type { InputProps } from '@/components/ui/Input'
export { Textarea } from '@/components/ui/Textarea'
export type { TextareaProps } from '@/components/ui/Textarea'
export { SearchInput } from '@/components/ui/SearchInput'
export type { SearchInputProps } from '@/components/ui/SearchInput'
export { Text } from '@/components/ui/Text'
export type { TextVariant } from '@/components/ui/Text'
export { Icon } from '@/components/ui/Icon'
export { GlassSurface } from '@/components/ui/GlassSurface'
export type { GlassSurfaceProps, GlassElevation } from '@/components/ui/GlassSurface'
export { Badge } from '@/components/ui/Badge'
export type { BadgeProps } from '@/components/ui/Badge'
export { StatusChip } from '@/components/ui/StatusChip'
export type { StatusChipProps } from '@/components/ui/StatusChip'
export { Alert } from '@/components/ui/Alert'
export type { AlertProps, AlertVariant } from '@/components/ui/Alert'
export { Skeleton } from '@/components/ui/Skeleton'
export type { SkeletonProps } from '@/components/ui/Skeleton'

// Phase 3 — Complex & Layout Primitives
export { Dropdown } from '@/components/ui/Dropdown'
export type { DropdownProps, DropdownOption } from '@/components/ui/Dropdown'
export { Dialog } from '@/components/ui/Dialog'
export type { DialogProps } from '@/components/ui/Dialog'
export { Table, TableHead, TableBody, TableRow, TableTh, TableTd } from '@/components/ui/Table'
export { Pagination } from '@/components/ui/Pagination'
export type { PaginationProps } from '@/components/ui/Pagination'
export { Navbar } from '@/components/ui/Navbar'
export type { NavbarProps } from '@/components/ui/Navbar'
export { Sidebar } from '@/components/ui/Sidebar'
export type { SidebarProps, SidebarSection, SidebarNavItem } from '@/components/ui/Sidebar'
export { NotificationPanel } from '@/components/ui/NotificationPanel'
export type { NotificationPanelProps, NotificationItem } from '@/components/ui/NotificationPanel'
export { Timeline } from '@/components/ui/Timeline'
export type { TimelineProps, TimelineItem, TimelineItemVariant } from '@/components/ui/Timeline'
export { AIRecommendationCard } from '@/components/ui/AIRecommendationCard'
export type { AIRecommendationCardProps, AIField } from '@/components/ui/AIRecommendationCard'
